---
#Top of SPEC benchmark tree is '/usr/local/benchmark/speccpu2006/speccpu2006'
#Tools built successfully.  Go to the top of the tree and
#source the shrc file.  Then you should be ready.

- name: create speccpu2006 directory
  file: path=/usr/local/benchmark/speccpu2006 state=directory mode=0755

- name: Install deps packages via yum
  yum: name={{ item }} state=present
  when: ansible_os_family == 'RedHat'
  with_items:
  - automake
  - numactl
  - gcc
  - gcc-c++
  - gcc-gfortran
  - libgfortran
  - libgcc
  - glibc
  - glibc-devel
  - libstdc++
  - libstdc++-devel

- name: Install deps packages via apt
  apt: name={{ item }} state=present
  when: ansible_os_family == 'Debian'
  with_items:
  - automake
  - numactl
  - gcc
  - g++
  - libgfortran-5-dev

- name: copy scripts to targetpath
  copy: src=scripts dest=/usr/local/benchmark/speccpu2006 mode=0755


- name: downlaod SPECJVM2008 to dest
  get_url:
    url: ftp://ftp:123456@htsat.vicp.cc/speccpu2006.tar.gz
    dest: /usr/local/benchmark/speccpu2006
    mode: 0755
  tags: spec1
#temporary schedule
# replace of ftp server on the future
- name: Decompress speccpu2006 tarball
  unarchive:
    src: /usr/local/benchmark/speccpu2006/speccpu2006.tar.gz
    dest: /usr/local/benchmark/speccpu2006/
    copy: yes
    list_files: yes
  tags: spec2

- name: Configure speccpu2006 envriment
  lineinfile: dest=/etc/profile line='export FORCE_UNSAFE_CONFIGURE=1' insertafter='EOF'
  #command: source /etc/profile
  tags: spec3

- name: build speccpu2006 
  #copy: src=scripts/buildtools dest=/usr/local/benchmark/speccpu2006/speccpu2006/tools/src mode=0755
  shell: source /etc/profile && echo y | ./buildtools 
  args:
    chdir: /usr/local/benchmark/speccpu2006/speccpu2006/tools/src

  #when: ansible_distribution == "Ubuntu"
  tags: spec4


